#
name: crypt-info
environment: dev

server:
  port: 5000

logging:
  level:
    .: debug
    org.springframework: DEBUG
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql: trace
  file:
    name: ${HOME}/logs/crypt-info.log

app:
  name: ${name}
  api-info-title: crypt-info REST API
  api-info-description: REST API crypt-info description
  api-info-version: /v1
  api-info-license: MIT
  api-info-license-url: https://opensource.org/licenses/MIT
  contact-name: crypt-info inc.
  contact-url: www.crypt-info.org
  contact-email: info@crypt-info.org
  base-package: io.github.astrapi69.crypt.info
  docket-paths-regex: ${app.api-info-version}/.*|
  dir: ${user.home}/.${app.name}
  db-name: cryptinfo
  db-host: localhost
  db-port: 5432
  db-username: postgres
  db-password: postgres
  db-url-prefix: jdbc:postgresql://
  printing-mode-on: false

spring:
  main:
    allow-bean-definition-overriding: false
  datasource:
    username: ${app.db-username}
    password: ${app.db-password}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: ${app.db-url-prefix}${app.db-host}:${app.db-port}/${app.db-name}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create
      show_sql: true
      use_sql_comments: true
      format_sql: true
      generate_statistics: false

  flyway:
    enabled: false
    baseline-on-migrate: true
  config:
    activate:
      on-profile: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      mode: never
