#
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:cryptinfo.db
  application:
    admin:
      enabled: false
      jmx-name: org.springframework.boot:type=Admin,name=SpringBootApplicationRunner
